### ISSUE TITLE
Null Pointer Except when trying to use 'Shape Interpolation'

### ISSUE THREAD

**Issue by tibuch** [saalfeldlab/paintera#545] opened 2024-07-31 15:03 UTC
Hi everyone,

I am trying to use the shape interpolation feature but I encounter this exception:
```
2024-07-31 17:00:54,430 27497   66939 [JavaFX Application Thread] ERROR org.janelia.saalfeldlab.fx.actions.ActionSet-Filter - Shape Interpolation Paint Brush Actions: provide shape interpolation mask to paint brush (MOUSE_PRESSED was valid, but failed
java.lang.NullPointerException: null
	at org.janelia.saalfeldlab.paintera.control.ShapeInterpolationController.getCurrentBestMipMapLevel$paintera(ShapeInterpolationController.kt:128)
	at org.janelia.saalfeldlab.paintera.control.ShapeInterpolationController.getMask$default(ShapeInterpolationController.kt:631)
	at org.janelia.saalfeldlab.paintera.control.tools.shapeinterpolation.ShapeInterpolationPaintBrushTool$extraActions$1$1$2.invoke(ShapeInterpolationPaintBrushTool.kt:92)
	at org.janelia.saalfeldlab.paintera.control.tools.shapeinterpolation.ShapeInterpolationPaintBrushTool$extraActions$1$1$2.invoke(ShapeInterpolationPaintBrushTool.kt:87)
	at org.janelia.saalfeldlab.fx.actions.Action.invoke(Action.kt:306)
	at org.janelia.saalfeldlab.fx.actions.ActionSet.invoke(ActionSet.kt:392)
	at org.janelia.saalfeldlab.fx.actions.ActionSet.access$invoke(ActionSet.kt:53)
	at org.janelia.saalfeldlab.fx.actions.ActionSet$ActionSetActionEventHandler.handle(ActionSet.kt:429)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventFilterRecord.handleCapturingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchCapturingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchCapturingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at javafx.graphics/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

I tested versions 1.3.4, 1.3.3, and 1.2.3. But I encounter the issue with all of them. I suspect some user error on my side, since I couldn't find any other reports of this problem.

**Comment by cmhulbert** [comment] 2024-07-31 18:58
The specific line that's giving the NPE seems to be when it's checking for the current active viewer (that is, which of the 3 ortho-slice panes is active to use for shape interpolation). 

I'm not sure why you are seeing this, as you mentioned, I haven't seen this before to my knowledge. That said, can you verify that one of the 3 ortho-slice pane views has a red cross-hair? That indicates that it is the active view. If you are activating the shape-interpolation mode with the button in the top-right, then maybe see if the hotkey works for now instead, which is `S`. Or, vice-versa, if the error is occuring currently with the hotkey (if you are using the button in the top left to enter shape interpolation, you should see the mouse cursor change to a cross hair of its own, and some text as the bottom indicating that you need to select the view you want to use Shape Interpolation in).

I'll see if I can't reproduce this, or if nothing else, add some additional checks to avoid this issue.

Let me know if any of these suggestions help for the meantime. If not, I'm happy to try and dig in a bit more to figure out what's going on

**Comment by tibuch** [comment] 2024-07-31 19:20
Thank you for the swift reply.

> I'm not sure why you are seeing this, as you mentioned, I haven't seen this before to my knowledge. That said, can you verify that one of the 3 ortho-slice pane views has a red cross-hair? That indicates that it is the active view. If you are activating the shape-interpolation mode with the button in the top-right, then maybe see if the hotkey works for now instead, which is `S`. Or, vice-versa, if the error is occuring currently with the hotkey (if you are using the button in the top left to enter shape interpolation, you should see the mouse cursor change to a cross hair of its own, and some text as the bottom indicating that you need to select the view you want to use Shape Interpolation in).

I am able to reproduce the described behavior. I am over one of the ortho-views as indicated by the red cross, by pressing `S` I switch into the `shape interpolation` mode. However, once I want to start drawing (either by pressing the draw button or using space), nothing is being drawn and the exception appears. I see the brush-circle, but nothing happens on drag. 

When no ortho-view is selected and I press the `shape interpolation` button, I get the cross to select the ortho-view. This works and the UI switches as well. Then trying to draw fails as described above.

**Comment by cmhulbert** [comment] 2024-07-31 19:40
Thanks (and sorry) for reproducing. If you can, can you increase the log level to `DEBUG` by:
 1.  Opening the side panel with `P`
 2. Settings -> Logging
 3. set the `ROOT` log level to `DEBUG
 
Then trigger the issues again (maybe a few times, for good measure), and share the log file? You can find the log file location by clicking the button  in the `Settings` -> `Logging` panel, with the icon of two folder papers. When you click on that, it should copy the full path of the log file to your clipboard, then I think you can attach it to this issue in a comment. That should help me determine how this is occurring.

**Comment by tibuch** [comment] 2024-07-31 19:54
I don't know what happened, but I can't get the bug anymore. :shrug: 

I had it 30min ago, restarted paintera (this is not the first time I restarted paintera) and now it just works as expected. 

The only difference to this afternoon is, that I am now at home on my couch and I have no external screen connected. However, it did fail 30min ago, without the external screen. Furthermore, this afternoon, it also failed on my colleagues laptop which runs on Windows (I am on Ubuntu). 

Another difference: I opened an issue on GitHub and got a response :smile: 

I will try again at work (on Monday, long weekend over here :sunglasses:). Feel free to close this.

**Comment by cmhulbert** [comment] 2024-07-31 20:29
Well, glad you are not experiencing the issue any more!

I'll close for now, but feel free to open up again if you see it again. Hopefully not, but these types of bugs can be pernicious, so either way 🤷‍♀️ 

Enjoy the long weekend!

**Comment by tibuch** [comment] 2024-08-06 07:31
I am back :sweat: 

I tried again this morning back at work and got this log:

```
2024-08-06 09:28:31,745 25978   12718 [JavaFX Application Thread] INFO  org.janelia.saalfeldlab.paintera.data.mask.MaskedSource - Updating cache directory: observable=StringProperty [value: /home/tibuch/.cache/paintera/canvases/canvas-6467796234893147338] oldValue=null newValue=/home/tibuch/.cache/paintera/canvases/canvas-6467796234893147338
2024-08-06 09:28:57,199 51432   12718 [JavaFX Application Thread] ERROR org.janelia.saalfeldlab.fx.actions.ActionSet-Filter - Shape Interpolation Paint Brush Actions: provide shape interpolation mask to paint brush (MOUSE_PRESSED was valid, but failed
java.lang.NullPointerException: null
	at org.janelia.saalfeldlab.paintera.control.ShapeInterpolationController.getCurrentBestMipMapLevel$paintera(ShapeInterpolationController.kt:128)
	at org.janelia.saalfeldlab.paintera.control.ShapeInterpolationController.getMask$default(ShapeInterpolationController.kt:631)
	at org.janelia.saalfeldlab.paintera.control.tools.shapeinterpolation.ShapeInterpolationPaintBrushTool$extraActions$1$1$2.invoke(ShapeInterpolationPaintBrushTool.kt:92)
	at org.janelia.saalfeldlab.paintera.control.tools.shapeinterpolation.ShapeInterpolationPaintBrushTool$extraActions$1$1$2.invoke(ShapeInterpolationPaintBrushTool.kt:87)
	at org.janelia.saalfeldlab.fx.actions.Action.invoke(Action.kt:306)
	at org.janelia.saalfeldlab.fx.actions.ActionSet.invoke(ActionSet.kt:392)
	at org.janelia.saalfeldlab.fx.actions.ActionSet.access$invoke(ActionSet.kt:53)
	at org.janelia.saalfeldlab.fx.actions.ActionSet$ActionSetActionEventHandler.handle(ActionSet.kt:429)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventFilterRecord.handleCapturingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchCapturingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchCapturingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at javafx.graphics/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by tibuch** [comment] 2024-08-06 08:15
Maybe this is not the real issue, but this is:
```
2024-08-06 10:07:55,695 36392 [JavaFX Application Thread] INFO  org.janelia.saalfeldlab.paintera.data.mask.MaskedSource - Updating cache directory: observable=StringProperty [value: /home/tibuch/.cache/paintera/canvases/canvas-11488043431779836448] oldValue=null newValue=/home/tibuch/.cache/paintera/canvases/canvas-11488043431779836448
Exception in thread "JavaFX Application Thread" org.apache.http.client.ClientProtocolException: URI does not specify a valid host name: http://0.0.0.0:8000new_session_id
        at org.apache.http.impl.client.CloseableHttpClient.determineTarget(CloseableHttpClient.java:95)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at org.janelia.saalfeldlab.paintera.cache.SamEmbeddingLoaderCache.getSessionId(SamEmbeddingLoaderCache.kt:248)
        at org.janelia.saalfeldlab.paintera.cache.SamEmbeddingLoaderCache.access$getSessionId(SamEmbeddingLoaderCache.kt:51)
        at org.janelia.saalfeldlab.paintera.cache.SamEmbeddingLoaderCache$navigationId$2.invoke(SamEmbeddingLoaderCache.kt:65)
        at org.janelia.saalfeldlab.paintera.cache.SamEmbeddingLoaderCache$navigationId$2.invoke(SamEmbeddingLoaderCache.kt:65)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.janelia.saalfeldlab.paintera.cache.SamEmbeddingLoaderCache.getNavigationId(SamEmbeddingLoaderCache.kt:65)
        at org.janelia.saalfeldlab.paintera.cache.SamEmbeddingLoaderCache.access$getNavigationId(SamEmbeddingLoaderCache.kt:51)
        at org.janelia.saalfeldlab.paintera.cache.SamEmbeddingLoaderCache$NavigationBasedRequestTimer.<init>(SamEmbeddingLoaderCache.kt:76)
        at org.janelia.saalfeldlab.paintera.cache.SamEmbeddingLoaderCache.startNavigationBasedRequests(SamEmbeddingLoaderCache.kt:118)
        at org.janelia.saalfeldlab.paintera.control.modes.ShapeInterpolationMode.enter(ShapeInterpolationMode.kt:121)
        at org.janelia.saalfeldlab.paintera.PainteraBaseView.lambda$new$6(PainteraBaseView.java:201)
        at javafx.base/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
        at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
        at javafx.base/javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(Unknown Source)
        at javafx.base/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
        at javafx.base/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
        at org.janelia.saalfeldlab.paintera.PainteraBaseView.changeMode(PainteraBaseView.java:254)
        at org.janelia.saalfeldlab.paintera.control.modes.PaintLabelMode$enterShapeInterpolationMode$1$1$4$switchModes$1.invoke(PaintLabelMode.kt:139)
        at org.janelia.saalfeldlab.paintera.control.modes.PaintLabelMode$enterShapeInterpolationMode$1$1$4$switchModes$1.invoke(PaintLabelMode.kt:137)
        at org.janelia.saalfeldlab.paintera.control.modes.PaintLabelMode$enterShapeInterpolationMode$1$1$4.invoke(PaintLabelMode.kt:147)
        at org.janelia.saalfeldlab.paintera.control.modes.PaintLabelMode$enterShapeInterpolationMode$1$1$4.invoke(PaintLabelMode.kt:136)
        at org.janelia.saalfeldlab.fx.actions.Action.invoke(Action.kt:306)
        at org.janelia.saalfeldlab.fx.actions.ActionSet.invoke(ActionSet.kt:392)
        at org.janelia.saalfeldlab.fx.actions.ActionSet.access$invoke(ActionSet.kt:53)
        at org.janelia.saalfeldlab.fx.actions.ActionSet$ActionSetActionEventHandler.handle(ActionSet.kt:429)
        at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
        at javafx.base/javafx.event.Event.fireEvent(Unknown Source)
        at javafx.graphics/javafx.scene.Scene.processKeyEvent(Unknown Source)
        at javafx.graphics/javafx.scene.Scene$ScenePeerListener.keyEvent(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.View.handleKeyEvent(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.View.notifyKey(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

We are behind a proxy and can't reach your SAM service. I setup a local SAM service on my laptop, for testing SAM, and provide the URI on startup via:
`SAM_SERVICE_HOST=http://0.0.0.0:8000 ./Paintera`

SAM works in the normal label drawing mode. However, when I enter `shape interpolation` mode I get the above error message. When I try to draw, I get the error message from the previous post.

**Comment by tibuch** [comment] 2024-08-06 08:42
This seems to be the issue. When I run Paintera outside of our proxy-protected network it works as it should. I can also use your SAM service. However, inside our network I can't reach your SAM service. And my local SAM service is only working in the label-drawing mode and gets the wrong URI inside the `shape interpolation` mode. 

I tried to provide the proxy settings with these commands:
```
JAVA_TOOL_OPTIONS='-Djava.net.useSystemProxies=true' ./Paintera
Picked up JAVA_TOOL_OPTIONS: -Djava.net.useSystemProxies=true
```

and

```
JAVA_TOOL_OPTIONS='-Dhttp.proxyHost=xxx.xx.xx.x -Dhttp.proxyPort=xxxx' ./Paintera
```

Then I tried SAM from the label-painting mode and got the following:
```
```

**Comment by imagejan** [comment] 2024-08-06 09:18
How about adding `useSystemProperties()` here:

https://github.com/saalfeldlab/paintera/blob/205269300954138a35c3fd646bbdf30c87b58ee6/src/main/kotlin/org/janelia/saalfeldlab/paintera/cache/SamEmbeddingLoaderCache.kt#L307

such that it reads:

```
val client = HttpClientBuilder.create().useSystemProperties().setDefaultRequestConfig(requestConfig).build()
```
?

---

Or adding proxy configuration explicitly to `properties.segmentAnythingConfig` and adding some logic here:

https://github.com/saalfeldlab/paintera/blob/205269300954138a35c3fd646bbdf30c87b58ee6/src/main/kotlin/org/janelia/saalfeldlab/paintera/cache/SamEmbeddingLoaderCache.kt#L122-L128

**Comment by cmhulbert** [comment] 2024-08-06 14:54
I'll look more into this, thanks for the stack traces and suggestions. 

In the meantime, can I suggest two things to try:
 1. When specifying the service host like you mentioned here `SAM_SERVICE_HOST=http://0.0.0.0:8000 ./Paintera` try to add a `/` at the end, after the port. It looks like the error you saw was due mostly to an incorrect request. I can ensure there is a `/` at the end in the future, but that may fix it for now
 2. You can also specify the `sam service host` in Paintera, and save it to your project by setting it under 
 `Settings -> Sam Service -> Service URL`. 
 
 @imagejan thanks for the suggestions, I think adding `useSystemProperties()` is a good idea for now.

**Comment by tibuch** [comment] 2024-08-06 15:29
Adding a `/` after the port works! Very nice :+1:

**Comment by cmhulbert** [comment] 2024-08-06 16:58
Glad to hear! I'll leave this open for now, and I'll close it when I merge those other changes in

**Closed** 2024-08-13 14:17 UTC
